apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiostar
  labels:
    app: jiostar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jiostar
  template:
    metadata:
      labels:
        app: jiostar
    spec:
      containers:
      - name: jioStat
        image: ghcr.io/codewithmitesh/jiostar-devops:sha-7a6c7cc89a057fa9612a1c7fb05d3201203ee3ba
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MOVIEDB_APIKEY
          valueFrom:
            secretKeyRef:
              name: moviedb-apikey
              key: MOVIEDB_APIKEY
      imagePullSecrets:
      - name: github-container-registry