apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiostar
  labels:
    app: jiostar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jiostar
  template:
    metadata:
      labels:
        app: jiostar
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - jiostar
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: jiostar
        image: ghcr.io/codewithmitesh/jiostar-devops:sha-4bdb7a1dbb4f236a0ce884a7331085a73976cc6f
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: run
          mountPath: /var/run/
        - name: tmp
          mountPath: /var/lib/nginx/tmp/
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: github-container-registry
      volumes:  
      - name: run
        emptyDir: {}
      - name: tmp
        emptyDir: {}